<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MouseBaseLib\MouseBaseLib.csproj" />
    <ProjectReference Include="..\MouseStdLib\MouseStdLib.csproj" />
    <ProjectReference Include="..\Tests\MouseLibTests\MouseLibTests.csproj" />
  </ItemGroup>

</Project>
